name: taskwarrior
description: A new Flutter project.
version: 2.0.0+2
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  connectivity_plus: ^6.1.3
  crypto: ^3.0.1
  cupertino_icons: ^1.0.5
  date_format: ^2.0.6
  double_back_to_close_app: ^2.1.0
  file_picker: ^9.0.2
  file_picker_writable: ^2.0.3
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_gen: ^5.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.1.2+1
  flutter_native_timezone: ^2.0.0
  flutter_platform_widgets: ^8.0.0
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.7
  flutter_test:
    sdk: flutter
  get: ^4.6.5
  get_test: ^4.0.1
  google_fonts: ^6.1.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  home_widget: ^0.7.0+1
  http: ^1.1.0
  import_sorter: ^4.6.0
  in_app_update: ^4.2.3
  intl: ^0.20.2
  loggy: ^2.0.1+1
  mockito: ^5.4.4
  package_info_plus: ^8.3.0
  pem: ^2.0.1
  permission_handler:
    git:
      url: https://github.com/bvoq/flutter-permission-handler.git
      path: permission_handler
      ref: master
  shared_preferences: ^2.2.2
  shared_preferences_web: ^2.0.3
  sizer: ^3.0.5
  sqflite: ^2.3.3+1
  syncfusion_flutter_charts: ^28.2.11
  test: ^1.25.2
  timezone: ^0.10.0
  tuple: ^2.0.0
  tutorial_coach_mark: ^1.2.11
  url_launcher: ^6.1.14
  uuid: ^4.2.2
  built_collection: ^5.1.1
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^5.0.0
  http_mock_adapter: ^0.6.1
  sqflite_common_ffi: ^2.0.0

flutter_gen:
  output: lib/app/utils/gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/SegoeUI.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
